#!/bin/bash
# FILE : bbpaint
# Function: "paints" all .jpg images in the directory. Simulates an oil painting.
# Copyright (C) 2006-2012 Dave Crouse <crouse@usalug.net>
# ------------------------------------------------------------------------ #
if [[ $1 = "--help" || $1 = "-h" || $1 = "help" ]]; then
       	echo "		Function: Paints all .jpg images in the directory. Simulates an oil painting."; 
	echo "		Usage: $0 brushsizenumber";
   	echo "		Requires: Imagemagick";
        echo "		EXAMPLE: $0 3";
	echo "		This would simulate an oil painting with a brush size 3.";
	echo "		1 to 5 produces the best resultes ;) ";
	echo "		Note: brushsize variable MUST be numeric ! ";
	echo "		";
   	echo "		Comments/Suggestions/Bugfixes to <crouse@usalug.net>";
   	echo "		USA Linux Users Group - http://usalug.org";
   	echo "		";
exit 0
fi

if [[ -z $( type -p convert ) ]]; then echo -e "ImageMagick -- NOT INSTALLED !";exit ;fi

if [[ -z "$1" || $1 = *[^0-9]* ]] ; then
	echo " ";
	echo "		######### COMMAND FAILED ########## ";
	echo "		USAGE: $0 brushsizenumber";
	echo "		EXAMPLE: $0 3";
	echo "		This would simulate an oil painting with a brush size 3.";
	echo "		1 to 5 produces the best resultes ;) ";
	echo "		Note: brushsize variable MUST be numeric ! ";
	echo "		######### COMMAND FAILED ########## ";echo " ";
else

export IFS=$'\n';
for i in $(find . -maxdepth 1 -type f -iname "*.jpg");
do 
convert -paint $1 ${i:2} _${i:2};
mv _${i:2} ${i:2}
echo "Painted image ${i:2}" ;
done
fi
exit 0
